### ISSUE TITLE
[small tip] Making Travis CI ensure Test Coverage Threshold

### ISSUE THREAD

**Issue by davin111** [swsnu/swppfall2019#167]
안녕하세요, 어제 실습한 Travis CI 연동 이후, 저희 팀 repo에 Travis CI가 test coverage를 일정 기준 되어야한다는 것을 충족시키야 pass해주도록 만들었는데, 이 방법을 공유드리고자 합니다. 물론 워낙 간단해서 이미 아시는 분들도 많을 것이고, 찾아보시면 금방 나오는 것이긴 합니다.

## How to make Travis CI ensure Test Coverage
**Frontend**
frontend directory의 package.json 파일을 수정해주시면 됩니다. 실습 5에서, 특정 파일에 대해서는 test하지 않도록 했던 것(collectCoverageFrom)과 비슷한 방식입니다. 예를 들어 아래와 같이 하면, 4가지 유형 coverage가 모두 90%를 넘어야만 한다는 것을 Travis CI가 frontend test를 돌릴 때 강제해줍니다.
```
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx}",
      "!src/index.js",
      "!src/serviceWorker.js"
    ],
    "coverageThreshold": {
      "global": {
        "branches": 90,
        "functions": 90,
        "lines": 90,
        "statements": 90
      }
    }
  }
```
만약 넘지 못하면 아래와 같은 출력을 Travis CI에서 보실 수 있습니다.
<img width="525" alt="스크린샷 2019-10-25 14 25 20" src="https://user-images.githubusercontent.com/35535636/67545214-4a182580-f733-11e9-8b6b-15490b2b254d.png">

**Backend**
backend의 경우, 실습 7에서 django test의 coverage를 보기 위해 사용한 coverage 라이브러리 방식을 사용하는 방식으로 가능합니다. 아래와 같이 하면, 역시 django coverage 90%를 준수하게 할 수 있습니다.
```
...
  - language: python
    python: 
    - "3.6"
    install:
    - pip install coverage
    script:
    - coverage run --source='.' ./backend/manage.py test # 물론 manage.py가 있는 경로에 맞게
    - coverage report --fail-under=90
...
```
만약 넘지 못하면 아래와 같은 출력을 Travis CI에서 보실 수 있습니다.
<img width="471" alt="스크린샷 2019-10-25 14 40 11" src="https://user-images.githubusercontent.com/35535636/67545774-5c935e80-f735-11e9-8c20-3e47b308a212.png">
